version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
    environment:
      XDEBUG_ENABLED: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_MAXNESTING_LEVEL: 1000
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_REMOTE_PORT: 9001
      #XDEBUG_REMOTE_LOG: /var/www/html/var/logs/xdebug.log

  mysql:
    container_name: mysql
    image: mysql:8.0.25
    expose:
      - 3306
    ports:
      - '3333:3306'
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aircodeblog
      MYSQL_USER: aircodeblog
      MYSQL_PASSWORD: aircodeblog

  memcached:
    container_name: memcached
    image: memcached:1.6.9
    ports:
      - 11211

  redis:
    container_name: redis
    image: redis:6.2.4-alpine
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  mysql:
    driver: local
  redis:
    driver: local
